version: "3.1"

services:
  init:
    image: airbyte/init:${VERSION}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: airbyte-config/init
      labels:
        io.airbyte.git-revision: ${GIT_REVISION}
  db:
    image: airbyte/db:${VERSION}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: airbyte-db
      labels:
        io.airbyte.git-revision: ${GIT_REVISION}
  seed:
    image: airbyte/seed:${VERSION}
    platform: linux/amd64
    build:
      dockerfile: seed.Dockerfile
      context: airbyte-server
      labels:
        io.airbyte.git-revision: ${GIT_REVISION}
  scheduler:
    image: airbyte/scheduler:${VERSION}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: airbyte-scheduler/app
      labels:
        io.airbyte.git-revision: ${GIT_REVISION}
  server:
    image: airbyte/server:${VERSION}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: airbyte-server
      labels:
        io.airbyte.git-revision: ${GIT_REVISION}
  webapp:
    image: airbyte/webapp:${VERSION}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: airbyte-webapp
      labels:
        io.airbyte.git-revision: ${GIT_REVISION}
  migration:
    image: airbyte/migration:${VERSION}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: airbyte-migration
      labels:
        io.airbyte.git-revision: ${GIT_REVISION}
